"""Generate big Mario sprite sheet (16x32, 7 frames)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from nes_palette import *

CM = {'R': MR, 'S': MS, 'B': MB}

# Frame 0: Big Mario Idle
idle = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '......SSSSSS....',
    '....RRSRRRSR....',
    '...SRRRSRRRSSS..',
    '...SRRRSSRRRSSS.',
    '...SS.RRRRRR.S..',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '....RRR...RRR...',
    '....RR.....RR...',
    '...SSSS...SSSS..',
    '..SSSSS...SSSSS.',
    '..SSSS.....SSSS.',
    '..SSS.......SSS.',
    '..BBB.......BBB.',
    '.BBBB.......BBBB',
    '.BBBB.......BBBB',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 1: Big Mario Walk 1
walk1 = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '......RRSRRR....',
    '.....RRRRRRRR...',
    '....SSRRRSRRRS..',
    '....SSSRRRRRRS..',
    '....SS.RRRRRR...',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '....RR.....RR...',
    '...SSSS...SSS...',
    '..SSSSS..SSSS...',
    '..SSSS...SSS....',
    '..SSS....SS.....',
    '..BBB...BBB.....',
    '.BBBB..BBBB.....',
    '.BBBB...........',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 2: Big Mario Walk 2
walk2 = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '......SSSSSS....',
    '....RRSRRRSR....',
    '...SRRRSRRRSSS..',
    '...SRRRSSRRRSSS.',
    '...SS.RRRRRR.S..',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '....RRR...RRR...',
    '...SSSS...SSSS..',
    '..SSSSS...SSSSS.',
    '..SSSS.....SSSS.',
    '..SSS.......SSS.',
    '..BBB.......BBB.',
    '.BBBB.......BBBB',
    '.BBBB.......BBBB',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 3: Big Mario Walk 3
walk3 = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '.....RRRSRR.....',
    '....RRRRRRRRS...',
    '...SRRRRSRRRSS..',
    '...SRRRRRRSSS...',
    '....RRRRRR.SS...',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '....RR.....RR...',
    '...SSS....SSSS..',
    '...SSSS..SSSSS..',
    '....SSS...SSSS..',
    '.....SS....SSS..',
    '.....BBB...BBB..',
    '.....BBBB.BBBB..',
    '...........BBBB.',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 4: Big Mario Jump
jump = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '......SSSSSS....',
    '...SRRSRRRSR....',
    '..SSRRRRRRRRSSS.',
    '..BSRRRRRRRRSB..',
    '..BB.RRRRRR.BB..',
    '.....RRRRRR.....',
    '....RRRRRRRR....',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '...RR.......RR..',
    '..SSSS....SSSS..',
    '.SSSSS....SSSSS.',
    '.SSSS......SSSS.',
    '.SSS........SSS.',
    '.BBB........BBB.',
    'BBBB........BBBB',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 5: Big Mario Skid
skid = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '......SSSSSS....',
    '...RRSRRRRS.....',
    '..SRRRRRRRRRR...',
    '..SSRRRRRRRRS...',
    '..SS.RRRRRR.S...',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '....RRR...RR....',
    '...SSSS..SSSS...',
    '..SSSSS.SSSSS...',
    '..SSSS...SSSS...',
    '..SSS.....SSS...',
    '..BBB.....BBB...',
    '.BBBB.....BBBB..',
    '......BBBB......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

# Frame 6: Big Mario Die (same as small die concept, scaled up)
die = sprite_from_rows([
    '................',
    '......RRRRR.....',
    '.....RRRRRRRRR..',
    '.....BBBSSBS....',
    '....BSBSSSBSSS..',
    '....BSBSSSBS.SS.',
    '....BBSSSSBB....',
    '...SSRRRRRRSS...',
    '..SSSRRSRRRSSS..',
    '..SSSRRSRRRSSS..',
    '..SS.RRRRRR.SS..',
    '......RRRRRR....',
    '.....RRRRRRRR...',
    '....RRRR.RRRR...',
    '....RRR...RRR...',
    '...RR.......RR..',
    '..SSSS....SSSS..',
    '.SSSSS....SSSSS.',
    '.SSSS......SSSS.',
    '.SSS........SSS.',
    '.BBB........BBB.',
    'BBBB........BBBB',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
], CM)

frames = [idle, walk1, walk2, walk3, jump, skid, die]
frames = [pad_frame(f, 16, 32) for f in frames]

img = create_sheet(frames, 16, 32)
out = os.path.join(os.path.dirname(__file__), '..', 'assets', 'sprites', 'mario_big.png')
img.save(out)
print(f"Saved {out} ({img.size[0]}x{img.size[1]})")
